import type { AnalysisResult } from "./types"

export const mockNewsArticles = [
  {
    id: "article-1",
    title: "Government Policy Update",
    text: "The government announced today a new policy aimed at reducing carbon emissions by 30% over the next decade. The policy includes tax incentives for renewable energy companies and stricter regulations for industrial polluters. Environmental experts have praised the move as a significant step forward in addressing climate change.",
  },
  {
    id: "article-2",
    title: "Election Results Disputed",
    text: "Opposition leaders have raised concerns about the integrity of yesterday's election results, citing irregularities in several voting districts. International observers reported some procedural issues but stated they did not appear to affect the overall outcome. The electoral commission has promised a thorough review of all complaints.",
  },
  {
    id: "article-3",
    title: "SHOCKING: Secret Government Program Exposed",
    text: "SHOCKING REVELATION: A whistleblower has exposed a secret government program that allegedly monitors citizens through their smart devices. According to anonymous sources, this surveillance has been ongoing for years without public knowledge or oversight. Government officials have REFUSED to comment on these explosive allegations.",
  },
  {
    id: "article-4",
    title: "Economic Growth Report",
    text: "The latest economic indicators show a 3.2% growth in GDP for the last quarter, exceeding analysts' expectations of 2.8%. Unemployment has fallen to a five-year low of 4.6%, while inflation remains stable at 2.1%. Economists attribute the positive performance to increased consumer spending and business investments.",
  },
  {
    id: "article-5",
    title: "COVID-19 Vaccine Conspiracy",
    text: "THEY DON'T WANT YOU TO KNOW: A group of independent researchers claims to have found evidence that COVID-19 vaccines contain microchips designed to track population movements. The pharmaceutical industry and global elites are allegedly behind this massive conspiracy to control the world population. SHARE BEFORE THIS GETS DELETED!",
  },
]

export const mockAnalysisHistory: AnalysisResult[] = [
  {
    id: "history-1",
    timestamp: "2025-03-15T14:23:45Z",
    text: "The government announced today a new policy aimed at reducing carbon emissions by 30% over the next decade. The policy includes tax incentives for renewable energy companies and stricter regulations for industrial polluters.",
    prediction: "REAL",
    probability: 0.92,
    keywords: ["government", "policy", "carbon", "emissions", "renewable", "energy", "regulations"],
    sentimentScore: 0.3,
    emotionalTone: {
      anger: 0.05,
      fear: 0.1,
      joy: 0.4,
      sadness: 0.05,
      surprise: 0.2,
    },
    sourceCredibility: 0.85,
    factualConsistency: 0.9,
  },
  {
    id: "history-2",
    timestamp: "2025-03-14T09:12:33Z",
    text: "SHOCKING REVELATION: A whistleblower has exposed a secret government program that allegedly monitors citizens through their smart devices. According to anonymous sources, this surveillance has been ongoing for years without public knowledge or oversight.",
    prediction: "FAKE",
    probability: 0.87,
    keywords: ["shocking", "revelation", "whistleblower", "secret", "surveillance", "anonymous", "sources"],
    sentimentScore: -0.6,
    emotionalTone: {
      anger: 0.3,
      fear: 0.7,
      joy: 0.05,
      sadness: 0.2,
      surprise: 0.8,
    },
    sourceCredibility: 0.25,
    factualConsistency: 0.3,
  },
  {
    id: "history-3",
    timestamp: "2025-03-13T16:45:12Z",
    text: "The latest economic indicators show a 3.2% growth in GDP for the last quarter, exceeding analysts' expectations of 2.8%. Unemployment has fallen to a five-year low of 4.6%, while inflation remains stable at 2.1%.",
    prediction: "REAL",
    probability: 0.95,
    keywords: ["economic", "indicators", "growth", "GDP", "unemployment", "inflation", "analysts"],
    sentimentScore: 0.7,
    emotionalTone: {
      anger: 0.02,
      fear: 0.05,
      joy: 0.6,
      sadness: 0.03,
      surprise: 0.3,
    },
    sourceCredibility: 0.9,
    factualConsistency: 0.95,
  },
  {
    id: "history-4",
    timestamp: "2025-03-12T11:33:27Z",
    text: "THEY DON'T WANT YOU TO KNOW: A group of independent researchers claims to have found evidence that COVID-19 vaccines contain microchips designed to track population movements. The pharmaceutical industry and global elites are allegedly behind this massive conspiracy.",
    prediction: "FAKE",
    probability: 0.98,
    keywords: ["they", "don't", "want", "know", "microchips", "vaccines", "conspiracy", "elites"],
    sentimentScore: -0.8,
    emotionalTone: {
      anger: 0.5,
      fear: 0.8,
      joy: 0.02,
      sadness: 0.3,
      surprise: 0.7,
    },
    sourceCredibility: 0.1,
    factualConsistency: 0.05,
  },
  {
    id: "history-5",
    timestamp: "2025-03-11T14:22:18Z",
    text: "Scientists at the University of Cambridge have published a new study in Nature showing promising results for a treatment that could slow the progression of Alzheimer's disease. The clinical trials involved 1,200 patients over a three-year period.",
    prediction: "REAL",
    probability: 0.91,
    keywords: ["scientists", "university", "cambridge", "study", "nature", "clinical", "trials", "alzheimer's"],
    sentimentScore: 0.6,
    emotionalTone: {
      anger: 0.01,
      fear: 0.1,
      joy: 0.5,
      sadness: 0.2,
      surprise: 0.4,
    },
    sourceCredibility: 0.95,
    factualConsistency: 0.9,
  },
  {
    id: "history-6",
    timestamp: "2025-03-10T09:15:42Z",
    text: "Breaking: Major political scandal as leaked documents reveal corruption at the highest levels of government. Sources close to the investigation suggest multiple arrests are imminent. The opposition is calling for immediate resignations.",
    prediction: "FAKE",
    probability: 0.75,
    keywords: ["breaking", "scandal", "leaked", "documents", "corruption", "sources", "investigation", "arrests"],
    sentimentScore: -0.5,
    emotionalTone: {
      anger: 0.6,
      fear: 0.4,
      joy: 0.05,
      sadness: 0.3,
      surprise: 0.7,
    },
    sourceCredibility: 0.4,
    factualConsistency: 0.5,
  },
]

